### ISSUE TITLE
初始化目录结构少了好多

### ISSUE THREAD

**Issue by shepherdwind** [react-component/generator-rc#3]
更新之后，yo rc后生成的只有一个src，其他examps和test怎么都没有了

**Comment by shepherdwind** [comment]
```
➜  accordion  tree
.
├── HISTORY.md
├── README.md
├── package.json
└── src
    ├── Accordion.jsx
    └── RcAccordion.jsx
```

**Comment by yiminghe** [comment]
卸掉重装？ 这边是好额啊

```
npm install yo generator-rc -g
```

**Comment by shepherdwind** [comment]
我重装过好多次，不知道是不是node版本的问题。我用的是2.3

**Comment by yiminghe** [comment]
fixed at 2.3.3  .npmignore 放在底层目录也起作用

**Comment by shepherdwind** [comment]
为啥会有这个问题？你也得默认安装iojs才行了，现在都没人用node了

**Comment by yiminghe** [comment]
和 node 版本没关系

之前接这个叫  .npmignore

https://github.com/react-component/generator-rc/blob/master/generators/app/templates/npmignore

忽略了很多东西
